### ISSUE TITLE
No Encryption?

### ISSUE THREAD

**Issue by cattyhouse** [heiher/hev-socks5-tproxy#1]
It's easy to get detected by GFW, do you think?

**Comment by heiher** [comment]
Yes, the standard socks5 proxy protocol is easy to detected by GFW. This is just a transparent proxy client that communicate with socks5 compatible server. We can use any obfuscation protocol for cross-border communication.

**Comment by cattyhouse** [comment]
Would you consider adding a Websocket and TLS1.3 layer on top of the socks5 protocol?

**Comment by heiher** [comment]
How to work? What can this solve?

**Comment by cattyhouse** [comment]
something like vmess+websocket+tls+nginx. replace vmess with socks5, you'll have user authentication via socks5 between server and client, as well as strong encryption and a standard https fingerprint, pretty safe.

**Comment by heiher** [comment]
Sounds good, I have a private project that implements a confusing protocol and seems works fine. I think it's better to implement a socks5 compatible server based on WebSocket and TLS, and use it in combination with this project?

**Comment by cattyhouse** [comment]
Yeah, good idea, you can put the sock5 server behind Nginx. Other confusing protocol won't live long.

**Comment by cattyhouse** [comment]
Any plan to add PURE tproxy support, so only mangle table is needed, and both udp and tcp are supported. 

Reference: 
https://www.kernel.org/doc/Documentation/networking/tproxy.txt

**Comment by cattyhouse** [comment]
I found that this program is very useful when work with Trojan

**Comment by heiher** [comment]
> Any plan to add PURE tproxy support, so only mangle table is needed, and both udp and tcp are supported.
> 
> Reference:
> https://www.kernel.org/doc/Documentation/networking/tproxy.txt

IIRC, the TPROXY target needs privilege capabilities.

**Comment by cattyhouse** [comment]
> > Any plan to add PURE tproxy support, so only mangle table is needed, and both udp and tcp are supported.
> > Reference:
> > https://www.kernel.org/doc/Documentation/networking/tproxy.txt
> 
> IIRC, the TPROXY target needs privilege capabilities.

Yes, that's correct, setcap can get things done so that No root privilege is needed to listen as tproxy.

**Comment by heiher** [comment]
> > > Any plan to add PURE tproxy support, so only mangle table is needed, and both udp and tcp are supported.
> > > Reference:
> > > https://www.kernel.org/doc/Documentation/networking/tproxy.txt
> > 
> > 
> > IIRC, the TPROXY target needs privilege capabilities.
> 
> Yes, that's correct, setcap can get things done so that No root privilege is needed to listen as tproxy.

This project is run as a module in JVM on Android, not a standalone process, may be can not set caps for it.

**Comment by cattyhouse** [comment]
OK, maybe add an option to listen as TPROXY?

**Comment by heiher** [comment]
> OK, maybe add an option to listen as TPROXY?

Yes.
