### ISSUE TITLE
Is "really" transparent proxy?

### ISSUE THREAD

**Issue by 0990** [heiher/hev-socks5-tproxy#13]
[redsocks](https://github.com/darkk/redsocks)说明自己并不是真实的透明代理：redsocks acts at TCP level, so three-way handshake is completed and redsocks accepts connection before connection through proxy (and to proxy) is established。我想问下这个项目也是这样的吗？

**Comment by heiher** [comment]
是的，应该只要是使用iptables TPROXY或nftables tproxy都是这样的行为。
