### ISSUE TITLE
consider using zig cc instead of musl.cc

### ISSUE THREAD

**Issue by cattyhouse** [heiher/hev-socks5-tproxy#17]
With zig cc, there is no need to download tool chains, as zig cc is able to prepare/compile needed libc for various arch on the fly. 

Build linux binary on macOS for instance:

```
make CC="zig cc -s -static -target x86_64-linux-musl" AR="zig ar"
```

[reference](https://andrewkelley.me/post/zig-cc-powerful-drop-in-replacement-gcc-clang.html)

**Comment by heiher** [comment]
Could you please create a pull request? Thanks.
