### ISSUE TITLE
hev-socks5-tproxy GUI for Andorid

### ISSUE THREAD

**Issue by SeeFlowerX** [heiher/hev-socks5-tproxy#18]
hev-socks5-tproxy有安卓版本，不知道是否可以简化配置步骤，做成GUI，就像[sockstun](https://github.com/heiher/sockstun)一样

当然前提条件是有root，另外还可以引入基于uid的过滤（--uid-owner）

**Comment by heiher** [comment]
以前有的，正是因为需要root权限比较麻烦，现在改成使用hev-socks5-tunnel实现了，好在经过优化后性能也不差的。

**Comment by SeeFlowerX** [comment]
安卓上不用VPN主要是能绕过一些不让开VPN用的软件（主要是用来抓包）

主要担心自己配iptables/ip6tables怕配不对，hev-socks5-tunnel看起来不用配置iptables了，我试试看

另外之前测试sockstun，发现得必须用DOT的DNS？

**Comment by heiher** [comment]
没有DOT要求

**Comment by SeeFlowerX** [comment]
可能是一些软件自己的处理逻辑，比如酷安，用114的dns就不行，查了下853是DOT用的，114不支持这个：

https://github.com/heiher/hev-socks5-tproxy/assets/70688581/15e6ffa5-68e5-4e41-a830-52f2739272d4

但是我用socksdroid就没有这个问题，它可以指定dns的端口（不知道是不是这个起作用了），不知道sockstun能针对这种情况优化一下？

![image](https://github.com/heiher/hev-socks5-tproxy/assets/70688581/6d532307-f550-4bb4-8153-0bfc7cfc8709)

**Comment by heiher** [comment]
开启VPN指定的DNS和不开VPN连接Wifi或移动数据连接一样的，后者也是使用运营商分配的DNS服务，它也不一定都支持DOT，那这些应用怎么能正常工作的呢？

**Comment by heiher** [comment]
Android 系统「设置」里的「私有DNS」配置为「关闭」试试？

**Comment by SeeFlowerX** [comment]
关闭私人DNS也是一样的。

过于底层我也没深入研究，应该是socksdroid对dns的处理机制不一样

socksdroid的dns端口最后是作为pdnsd配置里面的server，可能有一些fallback之类的行为。

- https://github.com/bndeff/socksdroid/blob/cf4d7babc40701c7c19d080198a2e7522fa8e617/app/src/main/java/net/typeblog/socks/SocksVpnService.java#L215

- https://github.com/bndeff/socksdroid/blob/cf4d7babc40701c7c19d080198a2e7522fa8e617/app/src/main/res/values/pdnsd.xml#L17

搜了下这个libpdnsd.so是ssr项目的，估计这个是防劫持的，这样反而不利于抓包验证了。
