### ISSUE TITLE
Segmentation fault built with zig cc $ARCH-linux-musl

### ISSUE THREAD

**Issue by cattyhouse** [heiher/hev-socks5-tproxy#21]
if the binary is built with  **zig cc ARCH-linux-musl**, Segmentation fault in 2 cases

1. https://github.com/heiher/hev-socks5-tproxy/issues/20#issuecomment-1879677060
> if change udp: 'udp' to udp: 'tcp', i know this mode only works with hev-socks5-server, it does not work with trojan-r socks5 listening. when sending a udp packet like dig @1.1.1.1 example.com (udp packet), hev-socks5-tproxy just exit with Segmentation fault, i know it will fail, but that could be handled better with some error message instead of exit with seg fault. (side note, in this case trojan-r log shows: socks: unsupported command 0x5), just some thoughts, not a big issue if one knows how to configure the udp:  parameter.

2. https://github.com/heiher/hev-socks5-tproxy/issues/20#issuecomment-1879500327
> i found another hev-socks5-tproxy Segmentation fault when upstream socks5 server stopped/killed/quit/no longer listening. can you reproduce this behavior on your side? 

not effected when using **zig cc ARCH-linux-`gnu`**, tested zig version 0.11,0.12-dev

build arg

```sh
# STRIP=true disables strip in Makefile, as we have zig cc -s to strip
make clean ;
make \
CC='zig cc -flto -O3 -s -static -target aarch64-linux-musl' \
AR='zig ar' \
RANLIB='zig ranlib' \
STRIP=true \
-j
````

EDIT: issue fix by setting **task-stack-size** in `config.yml` equal or larger than **8193**. Or even larger, e.g. : `16384` is preferred

**Comment by heiher** [comment]
I can't reproduce it here. :( I'm not sure if it's a specific compiler or C library that's causing the coroutine task's stack to overflow, but it's easily confirmed by increasing the stack space.

```yaml
misc:
   task-stack-size: 65536
```

**Comment by heiher** [comment]
Thanks for your feedback.

The stack size is page alihned, it's allocated by `mmap`.

**Comment by heiher** [comment]
Fixed: https://github.com/heiher/hev-socks5-tproxy/commit/c8f77442cb1796122dadbd6ac59fb81d80a4f0c3
