### ISSUE TITLE
为什么我总是搞不出NAT1?

### ISSUE THREAD

**Issue by CCCAUCHY** [heiher/hev-socks5-tproxy#25]
用singbox搞不定NAT1才来尝试本项目, 结果还是不行, 到底哪里有问题? nft配置已经照抄了, 本项目配置文件也简单的很

**Comment by heiher** [comment]
Socks5服务器端也需要是支持UDP Fullcone NAT并且防火墙允许入站，最终才能达到NAT1的效果。

**Comment by CCCAUCHY** [comment]
> Socks5服务器端也需要是支持UDP Fullcone NAT并且防火墙允许入站，最终才能达到NAT1的效果。

服务端也是hev, 防火墙全开的

**Comment by heiher** [comment]
怎么测试的？

**Comment by CCCAUCHY** [comment]
> 怎么测试的？

PS5自带的测试

**Comment by CCCAUCHY** [comment]
> 怎么测试的？

听闻tproxy原理上就不支持NAT1, 于是我换了hev-socks5-tunnel, 依旧是同样的结果

**Comment by heiher** [comment]
我找时间再确认一下

**Comment by heiher** [comment]
我再次实验验证了当前主线代码的UDP NAT1可用性，实验步骤和结果如下：

- S5服务器端：软件 hev-socks5-server 2.6.8 ，防火墙允许所有UDP入站，主机名记为S5S
- S5透明代理：软件 hev-socks5-tproxy 2.5.7
- UDP服务端：软件 tcpdump，有公网IP，防火墙允许指定端口UDP入站，主机名记为UDPS
- UDP客户端：软件 netcat + tcpdump，位于本地子网，上行流量通过S5透明代理，主机名记为UDPC
- UDP测试端：软件 netcat，主机名记为UDPT

1. 在主机UDPS上运行tcpdump，监听所有UDP流量入站，实时打印报文的源和目的地址信息。
2. 在主机UDPC上运行tcpdump，监听所有UDP流量入站，实时打印报文的源和目的地址信息。再运行nc命令向UDPS发送UDP报文。
3. 在主机UDPS上查看tcpdump输出，找出来自主机UDPC发送的UDP报文，记下源地址和端口（也就是S5S的地址）。
4. 在主机UDPT上运行nc命令，向步骤3获得的源地址端口发送UDP报文。
5. 在主机UDPC上查看tcpdump输出，查找来自主机UDPT的UDP测试报文。

我这的实验结果是在主机UDPC上可以收到来自主机UDPT的报文，说明由主机UDPC与主机UDPS创建的UDP会话可以接收来自三方主机UDPT的入站UDP报文，并且能正常转发至透明代理内网下的主机UDPC。

**Comment by heiher** [comment]
使用[NATMap](https://github.com/heiher/natmap)来测试更简单：

先确定域名`stun.freeswitch.org`的IP通过透明代理，再在经过透明代理的内网主机上运行：

```sh
nc -u -l -p 8000
natmap -u -s stun.freeswitch.org -t 127.0.0.1 -p 8000
```

最后在另外一台主机上做连接测试：

```sh
nc -u [natmap打洞获得的公网地址] [natmap打滑获得的公网端口]
```

发送UDP报文后，`nc -u -l -p 8000`可接收到，并且双向收发正常。

**Comment by CCCAUCHY** [comment]
> 使用[NATMap](https://github.com/heiher/natmap)来测试更简单：
> 
> 先确定域名`stun.freeswitch.org`的IP通过透明代理，再在经过透明代理的内网主机上运行：
> 
> ```shell
> nc -u -l -p 8000
> natmap -u -s stun.freeswitch.org -t 127.0.0.1 -p 8000
> ```
> 
> 最后在另外一台主机上做连接测试：
> 
> ```shell
> nc -u [natmap打洞获得的公网地址] [natmap打滑获得的公网端口]
> ```
> 
> 发送UDP报文后，`nc -u -l -p 8000`可接收到，并且双向收发正常。

nc命令通了之后是什么输出? 为什么我在服务器上 `nc -u -l -p 8000` `nc -u 127.0.0.1 8000` 也没有输出? 也抓不到包?
我决定改用[UDPping](https://github.com/wangyu-/UDPping)作为客户端, 虽然nc作为服务端时会显示超时, 但可以看到输出
UDPT可以是与UDPS相同类型的有公网IP的服务器吗?

**Comment by heiher** [comment]
> nc命令通了之后是什么输出? 为什么我在服务器上 nc -u -l -p 8000 nc -u 127.0.0.1 8000 也没有输出? 也抓不到包?

需要手工输入字符并回车才会发送报文。

>  UDPT可以是与UDPS相同类型的有公网IP的服务器吗?

UDPS需要有公网用作UDPC可达的目的地址；UDPT没有公网地址要求。

**Comment by CCCAUCHY** [comment]
> 使用[NATMap](https://github.com/heiher/natmap)来测试更简单：
> 
> 先确定域名`stun.freeswitch.org`的IP通过透明代理，再在经过透明代理的内网主机上运行：
> 
> ```shell
> nc -u -l -p 8000
> natmap -u -s stun.freeswitch.org -t 127.0.0.1 -p 8000
> ```
> 
> 最后在另外一台主机上做连接测试：
> 
> ```shell
> nc -u [natmap打洞获得的公网地址] [natmap打滑获得的公网端口]
> ```
> 
> 发送UDP报文后，`nc -u -l -p 8000`可接收到，并且双向收发正常。

由于测试条件比较寒酸, 省略了`nc -u -l -p 8000`, 在wsl2里运行`natmap -u -s stun.freeswitch.org -t 127.0.0.1 -p 8000`, 之后抓包查看发送到stun.freeswitch.org(147.182.188.245)的udp报文的源端口56579, 再用另一台vps运行nc, 传输内容"111", 过滤条件是目的端口为56579的udp, 抓到了传输内容为"111"的udp报文, 这是否能说明实现了NAT1?

**Comment by heiher** [comment]
> 由于测试条件比较寒酸, 省略了`nc -u -l -p 8000`, 因为wsl2还有一层NAT, wsl1无法运行natmap. 在wsl2里运行`natmap -u -s stun.freeswitch.org -t 127.0.0.1 -p 8000`, 之后抓包查看发送到stun.freeswitch.org(147.182.188.245)的udp报文的源端口56579, 再用另一台vps运行nc, 传输内容"111", 过滤条件是目的端口为56579的udp, 抓到了传输内容为"111"的udp报文, 这是否能说明实现了NAT1?

应该是。只要从另外一台主机发送到打洞获得的公网端口的报文能在内网抓到就行。

**Comment by CCCAUCHY** [comment]
> > 由于测试条件比较寒酸, 省略了`nc -u -l -p 8000`, 因为wsl2还有一层NAT, wsl1无法运行natmap. 在wsl2里运行`natmap -u -s stun.freeswitch.org -t 127.0.0.1 -p 8000`, 之后抓包查看发送到stun.freeswitch.org(147.182.188.245)的udp报文的源端口56579, 再用另一台vps运行nc, 传输内容"111", 过滤条件是目的端口为56579的udp, 抓到了传输内容为"111"的udp报文, 这是否能说明实现了NAT1?
> 
> 应该是。只要从另外一台主机发送到打洞获得的公网端口的报文能在内网抓到就行。

经过一年的学习，我现在主力系统换成了Linux，条件依旧有限，测试过程与您给的有所不同：
1. server1执行`tcpdump port 8000`
2. client执行`nc -u stun.freeswitch.org 8000`，键入内容111，不期待stun.freeswitch.org的回复
3. 在server1抓取目的地址为stun.freeswitch.org （143.198.60.79）且目的端口为8000的UDP数据包，抓到源端口为38336
4. server2与server1在同一个云服务虚拟子网里，server2执行`nc -u 10.0.0.66 38336`，键入内容222
5. 在client执行`nc -u stun.freeswitch.org 8000`所产生的命令行里，有如下内容：
```
111
222
```
其中111是第2步键入的，之后不再在client键入任何内容，那么222就是第4步键入并发送过来的

这样应该算证明实现NAT1了吧，代理软件不是hev

**Comment by heiher** [comment]
算是吧
