### ISSUE TITLE
readme很费解,请说明

### ISSUE THREAD

**Issue by flyhigao** [heiher/hev-socks5-tproxy#3]
看了下readme，几处很费解
1 redirect rule部分需要手动运行吗?
2 运行什么命令可以让普通程序使用sock5?
比如proxychains curl google.com,你的命令是什么?readme没写

**Comment by heiher** [comment]
项目的功能是通过透明代理(Transparent Proxy)的方式使 **Linux主机** 或是 **经过Linux网关的主机** 可以通过Socks5代理服务器来访问网络。透明代理的方式就是不需要干预应用程序，比如向proxychains一样增加前辍命令。透明代理可以通过IP地址集合、策略路由及本地DNS多源解析等匹配技术实现智能分流，控制只有部分流量经过代理服务器。

项目本身是透明代理的关键基础逻辑部分，但不包含重定向规则的自动维护，需要参考README结合实际需求来手工配置。

**Comment by flyhigao** [comment]
我看到您的帖子 https://hev.cc/2813.html ,里面说得很清楚, 该帖子的方案还可以生效吗? 那是2019年的版本了

**Comment by heiher** [comment]
这是类似于proxychains的前辍命令方式，脚本会自行维护规则，支持代理Go程序。我已经好久没有使用这种方式了，你试试看吧~

前辍脚本：https://github.com/heiher/hev-socks5-tproxy/blob/master/scripts/tp
