### ISSUE TITLE
work with trojan socks5

### ISSUE THREAD

**Issue by cattyhouse** [heiher/hev-socks5-tproxy#7]
one of the good idea of hev-socks5-tproxy is that it's upd tproxy is routed over tcp, which works quite well with Chrome youtube QUIC traffic in this way : [tproxy - socks5 upstream 10808] - > [trojan forward mode :  localhost 10808 to remote localhost 1080] - [trojan server 443] - [hev socks5 server port 1080]

is it possible to work directly with trojan client mode socks5 listening somehow?

**Comment by heiher** [comment]
> one of the good idea of hev-socks5-tproxy is that it's upd tproxy is routed over tcp, which works quite well with Chrome youtube QUIC traffic in this way : [tproxy - socks5 upstream 10808] - > [trojan forward mode : localhost 10808 to remote localhost 1080] - [trojan server 443] - [hev socks5 server port 1080]
> 
> is it possible to work directly with trojan client mode socks5 listening somehow?

No. The UDP over TCP is a non-standard extented command of socks5, it's now just only works with hev-socks5-server. I think forward TCP port is a nice way. 👍

**Comment by cattyhouse** [comment]
> > one of the good idea of hev-socks5-tproxy is that it's upd tproxy is routed over tcp, which works quite well with Chrome youtube QUIC traffic in this way : [tproxy - socks5 upstream 10808] - > [trojan forward mode : localhost 10808 to remote localhost 1080] - [trojan server 443] - [hev socks5 server port 1080]
> > is it possible to work directly with trojan client mode socks5 listening somehow?
> 
> No. The UDP over TCP is a non-standard extented command of socks5, it's now just only works with hev-socks5-server. I think forward TCP port is a nice way. 👍

Yeah, i have to. before this, i use [ipt2socks](https://github.com/zfl9/ipt2socks) to provide tproxy and forward to trojan client's socks5 port, it works very well, excecpt for QUIC traffic from Google Chrome and iOS youtube.app.

**Comment by heiher** [comment]
There have a [socks5 core ](https://github.com/heiher/hev-socks5-core)library that supports UDP over TCP, but I guess that non-standard feature may not be accepted by trojan.
